table: CountryVaccines
fields:
  - fieldName: UUID
    fieldType: string
    primaryKey: true
  - fieldName: CountryID
    fieldType: string
    notNull: true
  - fieldName: VaccineID
    fieldType: string
    notNull: true
  - fieldName: ValidS
    fieldType: string
    notNull: true
  - fieldName: CreatedAt
    fieldType: timestamp
  - fieldName: UpdatedAt
    fieldType: timestamp
  - fieldName: DeletedAt
    fieldType: timestamp

views:
  - name: FindByCountryID
    type: READ
    config:
      multiReturn: true
      returnType: data
    query:
      fields:
        - fieldName: CountryID
          searchType: EQUALS
