table: UserVaccines
fields:
  - fieldName: UUID
    fieldType: string
    primaryKey: true
  - fieldName: UserDocID
    fieldType: string
    notNull: true
  - fieldName: VaccineID
    fieldType: string
    notNull: true
  - fieldName: VaccineAuthorityID
    fieldType: string
    notNull: true
  - fieldName: VaccinationDate
    fieldType: string
    notNull: true
  - fieldName: CreatedAt
    fieldType: timestamp
  - fieldName: UpdatedAt
    fieldType: timestamp
  - fieldName: DeletedAt
    fieldType: timestamp

views:
  - name: FindByUserDocID
    type: READ
    config:
      multiReturn: true
      returnType: data
    query:
      fields:
        - fieldName: UserDocID
          searchType: CONTAINS
#
#  - name: CreateUser
#    type: CREATE
#    config:
#      returnType: primaryKey
#      multiReturn: true
#
#  - name: UpdateUsers
#    type: UPDATE
#    config:
#      multiInput: true
#      returnType: data
#      multiReturn: true
#
#  - name: DeleteUsers
#    type: DELETE
#    config:
#      multiInput: true
#      returnType: rowCount
#
