table: UserDocs
fields:
  - fieldName: UUID
    fieldType: string
    primaryKey: true
  - fieldName: UserID
    fieldType: string
    notNull: true
  - fieldName: OfficialID
    fieldType: string
    notNull: true
  - fieldName: OfficialIDType
    fieldType: string
    notNull: true
  - fieldName: IssuingCountryID
    fieldType: string
    notNull: true
  - fieldName: CreatedAt
    fieldType: timestamp
  - fieldName: UpdatedAt
    fieldType: timestamp
  - fieldName: DeletedAt
    fieldType: timestamp
views:
  - name: FindByUserID
    type: READ
    config:
      multiReturn: true
      returnType: data
    query:
      fields:
        - fieldName: UserID
          searchType: EQUALS


