table: Vaccines
fields:
  - fieldName: UUID
    fieldType: string
    primaryKey: true
  - fieldName: Name
    fieldType: string
    notNull: true
  - fieldName: CreatedAt
    fieldType: timestamp
  - fieldName: UpdatedAt
    fieldType: timestamp
  - fieldName: DeletedAt
    fieldType: timestamp

views:
  - name: FindByVaccineID
    type: READ
    config:
      multiReturn: true
      returnType: data
    query:
      fields:
        - fieldName: UUID
          searchType: CONTAINS